package governance

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Evidence is the §6 evidence pack, generated by the BFF for
// publish / promote-approve / promote-reject / sub-approve / sub-reject and
// committed IN THE SAME COMMIT as the action (never in volatile CI logs).
type Evidence struct {
	Action   string         `json:"action"`
	Actor    EvidenceActor  `json:"actor"`
	Tenant   string         `json:"tenant"`
	Resource string         `json:"resource"`
	Request  map[string]any `json:"request"`
	Checks   map[string]any `json:"checks"`
	Result   map[string]any `json:"result"`
	Negative string         `json:"negative,omitempty"`
}

// EvidenceActor identifies who performed the governed action.
type EvidenceActor struct {
	Username string   `json:"username"`
	Name     string   `json:"name"`
	Email    string   `json:"email"`
	Roles    []string `json:"roles"`
}

// EvidenceFiles renders the pack as {path}.json plus its .md twin
// (EVIDENCE.md skeleton: thèse → action → résultat → contrôles → limites).
// jsonPath must end in ".json".
func EvidenceFiles(jsonPath string, ev Evidence) (map[string][]byte, error) {
	raw, err := json.MarshalIndent(ev, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal evidence: %w", err)
	}
	mdPath := strings.TrimSuffix(jsonPath, ".json") + ".md"
	return map[string][]byte{
		jsonPath: append(raw, '\n'),
		mdPath:   renderEvidenceMD(ev),
	}, nil
}

// renderEvidenceMD writes the human-readable twin in French (the demo
// language), following the EVIDENCE.md skeleton.
func renderEvidenceMD(ev Evidence) []byte {
	var b strings.Builder
	now := time.Now().UTC().Format(time.RFC3339)

	fmt.Fprintf(&b, "# Évidence — %s (%s/%s)\n\n", ev.Action, ev.Tenant, ev.Resource)
	fmt.Fprintf(&b, "> Générée par governance-api le %s. L'évidence vit dans Git, dans le même commit que l'action.\n\n", now)

	b.WriteString("## Thèse\n\n")
	fmt.Fprintf(&b, "L'action `%s` sur `%s/%s` a été exécutée comme un commit gouverné : auteur identifié, contrôles passés, résultat vérifiable dans Git.\n\n",
		ev.Action, ev.Tenant, ev.Resource)

	b.WriteString("## Action\n\n")
	fmt.Fprintf(&b, "- **Acteur** : %s (%s) — rôles : %s\n", ev.Actor.Username, ev.Actor.Email, strings.Join(ev.Actor.Roles, ", "))
	fmt.Fprintf(&b, "- **Tenant** : %s\n", ev.Tenant)
	fmt.Fprintf(&b, "- **Ressource** : %s\n", ev.Resource)
	for _, k := range sortedKeys(ev.Request) {
		fmt.Fprintf(&b, "- **request.%s** : %v\n", k, ev.Request[k])
	}
	b.WriteString("\n")

	b.WriteString("## Résultat\n\n")
	if len(ev.Result) == 0 {
		b.WriteString("- (voir le commit contenant ce fichier)\n")
	}
	for _, k := range sortedKeys(ev.Result) {
		fmt.Fprintf(&b, "- **%s** : %v\n", k, ev.Result[k])
	}
	b.WriteString("\n")

	b.WriteString("## Contrôles\n\n")
	if len(ev.Checks) == 0 {
		b.WriteString("- aucun contrôle spécifique\n")
	}
	for _, k := range sortedKeys(ev.Checks) {
		fmt.Fprintf(&b, "- **%s** : %v\n", k, ev.Checks[k])
	}
	if ev.Negative != "" {
		fmt.Fprintf(&b, "- **contre-épreuve** : %s\n", ev.Negative)
	}
	b.WriteString("\n")

	b.WriteString("## Limites\n\n")
	b.WriteString("- Le SHA du commit porteur n'est pas inscrit dans ce fichier (il EST le commit qui le contient — œuf et poule) ; la réponse API et l'écran Audit le référencent.\n")
	b.WriteString("- PoC : signature SSH locale, allowed_signers géré par le seed — pas une PKI de production.\n")

	return []byte(b.String())
}

// sortedKeys gives deterministic rendering of the map sections.
func sortedKeys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j] < out[j-1]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}
